### ISSUE TITLE
Should we add non-Stencil solutions?

### ISSUE THREAD

**Issue by DavidFrahm** [mappmechanic/awesome-stenciljs#15]
Do you want non-Stencil things listed here? Asking because there isn't a working Stencil-specific solution for dynamic meta tags, but these web component libs from Polymer project work great for me:

https://github.com/Polymer/pwa-helpers

**Comment by balupton** [comment]
I think this listing's usecase is to showcase the power and adoption of stencil.

If you are just searching for web components to use yourself, then https://www.webcomponents.org is probably better served for you.

**Comment by mappmechanic** [comment]
Yes, this space is for people to find Awesome StencilJS solutions quickly. For anything other than that webcomponents.org is a perfect place.
